<%-- 
    Document   : RegistroUsuario
    Created on : 3/02/2016, 06:20:47 AM
    Author     : adsi
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>

<html >
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Untitled Form</title>
        <link rel="stylesheet" type="text/css" href="view.css" media="all">
        <script type="text/javascript" src="JS.js"></script>
       
    </head>

    <body id="main_body" >

        <img id="top" src="top.png" alt="">
        <div id="form_container">

            <h1><a>Untitled Form</a></h1>
            <form  name="formulario" id="form_1098143" class="appnitro"  method="post" action="Registro" >
                <div class="form_description">
                    <h2>Registro Usuarios</h2>
                    <p></p>
                </div>						
                <ul >

                    <li id="li_1" >
                        <label class="description" for="element_1">Usuario </label>
                        <div>
                            <input id="element_1" name="usuario" class="element text medium" type="text" maxlength="255" value="" onfocus="restaurar()"/> 
                        </div> 
                    </li>		<li id="li_2" >
                        <label class="description" for="element_2">Contraseña
                        </label>
                        <div>
                            <input id="element_2" name="contraseña" class="element text medium" type="text" maxlength="255" value="" onfocus="restaurar()"/> 
                        </div> 
                    </li>		<li id="li_3" >
                        <label class="description" for="element_3">Verificar contraseña </label>
                        <div>
                            <input id="element_3" name="verificar" class="element text medium" type="text" maxlength="255" value="" onfocus="restaurar()"/> 
                        </div> 
                    </li>		<li id="li_4" >
                        <label class="description" for="element_4">Telefono </label>
                        <div>
                            <input id="element_4" name="telefono" class="element text medium" type="text" maxlength="255" value="" onfocus="restaurar()"/> 
                        </div> 
                    </li>		<li id="li_5" >
                        <label class="description" for="element_5">Celular </label>
                        <div>
                            <input id="element_5" name="celular" class="element text medium" type="text" maxlength="255" value="" onfocus="restaurar()"/> 
                        </div> 
                    </li>

                    <li class="buttons">
                        <input type="hidden" name="form_id" value="1098143" />

                        <input id="saveForm" class="button_text" type="submit" name="submit" value="Submit"/>
                    </li>
                </ul>
            </form>	

            <p id="aviso"></p>
            <div id="footer">
                Generated by <a>Jr</a>
            </div>
        </div>
        <img id="bottom" src="bottom.png" alt="">
    </body>
</html>